### ISSUE TITLE
Cannot evaluate module react-native-facebook-login : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by ErSoul** [caioariede/uber-react#1] opened 2017-12-29 21:20 UTC
Hello, I have the following error when trying to run the app with the command react-native run-android:

```
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-facebook-login : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.267 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```
How can I solve this?

**Comment by simoesfelippe** [comment] 2018-02-05 12:52
Hello, did you solve the error? I have the same problem

**Comment by simoesfelippe** [comment] 2018-02-05 16:34
age in class FBSDKPackage cannot be applied to given types;
          new FBSDKPackage(),
          ^
  required: CallbackManager
  found: no arguments
  reason: actual and formal argument lists differ in length

**Comment by caioariede** [comment] 2018-07-06 11:09
Did any of you discover what the problem is? Please report if so, it might be useful for other people.

I'm closing this as it seems to be setup-related. Reopen if it's an issue with the code.

**Closed as completed by caioariede** 2018-07-06 11:09 UTC

**Comment by otaro808** [comment] 2018-08-01 08:21
You have to install module react-native-facebook-login separately to fix this.
Execute: npm i -S react-native-facebook-login
Refer to:
https://www.npmjs.com/package/react-native-fbsdk
